- name: Enable incoming connections for myproxy-server (TCP Port 7512)
  action: shell /usr/sbin/lokkit ${lokkit_flags} -p 7512:tcp
  notify:
    - restart iptables
- name: Enable incoming connections for bdii-core (TCP Port 2170)
  action: shell /usr/sbin/lokkit ${lokkit_flags} -p 2170:tcp
  notify:
    - restart iptables

