- name: Download epel-release package
  action: get_url url=${epel_release_url}/${epel_release_name} dest=/tmp/${epel_release_name} mode=0644
  environment: $proxy_env
- name: Install epel-release package
  action: command yum install -y ${yum_flags} /tmp/${epel_release_name} creates=/etc/yum.repos.d/epel.repo
  environment: $proxy_env
- name: Set priority for epel base only for nagios hosts
  action: lineinfile destfile="/etc/yum.repos.d/epel.repo" regexp="^priority" value="priority=50" state=present insertafter="repo=epel-5"
  only_if: '${is_nagios}'
